### ISSUE TITLE
Add some indication and a possibility to switch accounts during the verification flow.

### ISSUE THREAD

**Issue by jannes-io** [devcord/website#109]
See: https://discordapp.com/channels/174075418410876928/709133981483925654/750432436252311552

User was already logged in with a different account on discord web, causing him to be stuck since there is no option to review which discord account you are verifying with.

**Comment by AndresSweeneyRios** [comment]
I'll add a logout button.

**Comment by AndresSweeneyRios** [comment]
e6d2b37
