### ISSUE TITLE
Navigation current link & hover style

### ISSUE THREAD

**Issue by AndresSweeneyRios** [devcord/website#91]
- Probably should incorporate the red color from the previous website (#f0134d), currently the website doesn't have an accent color

![image](https://user-images.githubusercontent.com/20525464/90555737-af1e8b00-e14c-11ea-9a6e-8d89a2930e71.png)

**Comment by lostdesign** [comment]
Yes please, would consider it being our secondary color CI color after our gray.

**Comment by AndresSweeneyRios** [comment]
Hover style is done, does it actually need a current (active) style? Seems like it's not common elsewhere.
